import { Inter, Roboto,Merriweather,Poppins } from 'next/font/google'
import './globals.css'
import Header from './_components/Header'
import Footer from './_components/Footer'



const inter = Poppins({ subsets: ['latin'] ,weight :["400"]})

export const metadata = {
  title: 'BatoolForqan-School',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className=' '>

      <body className={`${inter.className} `}>


      <Header />
<main>
{children}
</main>
      
      
      {/* <NewHero /> */}
      
     
      
      
      
      
      <Footer />
      
      </body>
    </html>
  )
}
